# Generated by Django 6.0.4 on 2026-04-20 10:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mijoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(unique=True)),
                ('fullname', models.CharField(max_length=100)),
                ('phone1', models.CharField(max_length=20, unique=True)),
                ('phone2', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Sotuvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(unique=True)),
                ('fullname', models.CharField(max_length=100)),
                ('phone1', models.CharField(max_length=20, unique=True)),
                ('phone2', models.CharField(blank=True, max_length=20, null=True)),
                ('market_name', models.CharField(max_length=255, unique=True)),
                ('card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_images/')),
                ('market_id', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(10000, message="Market ID 5 raqamli bo'lishi kerak"), django.core.validators.MaxValueValidator(99999, message="Market ID 5 raqamli bo'lishi kerak")])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Qarzlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qarz_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pul_miqdori', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1000, message="Pul miqdori 1000 dan kam bo'lmasligi kerak"), django.core.validators.MaxValueValidator(3000000, message='Pul miqdori 3,000,000 dan oshmasligi kerak')])),
                ('qarz_sorov_tg_id', models.BigIntegerField()),
                ('qarz_tasdiq_tg_id', models.BigIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='qarz_images/')),
                ('status', models.CharField(choices=[('rad_qilingan', 'Rad qilingan'), ('tasdiqlangan', 'Tasdiqlangan'), ('kutilmoqda', 'Kutilmoqda')], default='kutilmoqda', max_length=20)),
                ('mijoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qarzlar', to='apps.mijoz')),
                ('sotuvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qarzlar', to='apps.sotuvchi')),
            ],
        ),
        migrations.AddField(
            model_name='mijoz',
            name='sotuvchilarim',
            field=models.ManyToManyField(blank=True, related_name='mijozlar', to='apps.sotuvchi'),
        ),
        migrations.CreateModel(
            name='Tolovlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pul_miqdori', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1000, message="Pul miqdori 1000 dan kam bo'lmasligi kerak"), django.core.validators.MaxValueValidator(3000000, message='Pul miqdori 3,000,000 dan oshmasligi kerak')])),
                ('tasdiq_time', models.DateTimeField(blank=True, null=True)),
                ('sotuvchi_tg_id', models.BigIntegerField()),
                ('mijoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tolovlar', to='apps.mijoz')),
                ('sotuvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tolovlar', to='apps.sotuvchi')),
            ],
        ),
    ]
